name: Pack Chrome Extension

on:
    push:
        branches: [main]
        tags:
            - 'v*'

jobs:
    pack:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Clone drawdown repository
              run: |
                  git clone https://github.com/adamvleggett/drawdown.git lib/drawdown

            - name: Install dependencies
              run: npm ci

            - name: Build extension
              run: npm run build

            - name: Pack extension
              run: |
                  mkdir -p packed-extension
                  cd dist
                  zip -r ../packed-extension/extension.zip .

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: packed-extension
                  path: packed-extension/extension.zip

            - name: Create Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: packed-extension/extension.zip
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
